### ISSUE TITLE
no online documentation

### ISSUE THREAD

**Issue by deronnax** [ashafer01/laurelin#1]
Hi.
Very nice project, but... no online documentation at all ?!

**Comment by ashafer01** [comment]
Hey! Really glad you like it. I will definitely write docs when things are more stable/complete. There are still some major things I haven't touched at all, and I may yet make some large changes to work already done.

**Comment by ashafer01** [comment]
Docs are up on [ReadTheDocs](http://laurelin-ldap.readthedocs.io/en/latest/index.html), including API docs and some more walkthrough-type stuff.
