### ISSUE TITLE
Should it work on Windows?

### ISSUE THREAD

**Issue by gowdy** [ashafer01/laurelin#12]
I'm looking to do a ldap query so trying out different methods. When I try to use it on Windows I get an import error;

  File "C:\ProgramData\Anaconda3\lib\site-packages\laurelin\ldap\net.py", line 8, in <module>
    from socket import create_connection, socket, AF_UNIX, error as SocketError
ImportError: cannot import name 'AF_UNIX'

**Comment by ashafer01** [comment]
I've added a fix for this issue and pushed version 1.4.1 to PyPI, please let me know if you encounter any more difficulty.
